# Available languages: en_US, fr_FR, pt_PT.
lang: en_US

episodes:
    enabled: true
    length: 20  # minutes
    syncTimer: true  # if true, the timer will be synchronized with a clock to avoid having long episodes because of lag

map:
    size: 2000
    circular: false
    wall:
        height: 128
        block:
            # The replaceAir block will be placed where there where some transparent blocks or trees before.
            # The replaceSolid one, where there was an other kind of block.
            replaceAir: GLASS
            replaceSolid: BEDROCK
    border:
        # The delay between two warning messages sent to the players out of a future border 
        # (this warning is set using /uh border warning <futureDiameter>).
        warningInterval: 90  # seconds

daylightCycle:
    do: false
    time: 6000  # Initial time (or game time if the daylight cycle is disabled) in ticks. 6000 = noon.


scoreboard:
    title: Kill the Patrick
    
    # Scoreboard displayed on the left of the screen
    enabled: true
    episode: true
    players: true
    teams: true
    timer: true
    freezeStatus: true
    
    # Health in the list of the players
    health: true

death:
    disablePvpFor: 600 # In ticks (1 second = 20 ticks)

    messages:
        notifyIfTeamHasFallen: true
        deathMessagesFormat: "ยง6"  # Use this to increase visibility of death messages.
        teamDeathMessagesFormat: "ยง6"
        
    kick:
        do: true
        time: 30
        allow-reconnect: true
        
    head:
        drop: true
        pvpOnly: false
        
    give-xp-to-killer:
        levels: 2  # set to 0 to disable
        onlyOtherTeam: true  # Give XP only if the player kills a player from another team?
        
    announcements:
        lightning-strike: false
        
        # Don't want any sound? Set this field to "NONE" (or any other value which is not a sound).
        # The available sounds can be found here: http://l.carrade.eu/bukkit-sounds .
        sound: WITHER_SPAWN

# If true, the name of the players will be colorized according to the teams.
colorizeChat: true

gameplay-changes:
    weather: true  # If false, the "bad" weather (rain, thunder) is disabled.
    
    replaceGhastTearsWithGold: true
    craftGoldenMelonWithGoldBlock: true
    
    craftGoldenAppleFromHead:
        fromHuman:
            do: true
            numberCrafted: 2
            addLore: true
            craftNotchApple: false
        fromWither:
            do: true
            numberCrafted: 1
            addLore: true
            craftNotchApple: false
    
    goldenApple:
        regeneration:
            # Half-hearts regenerated by one apple. Vanilla: normal 4, notch 180 (yes, 180).
            normal: 4
            notch: 180
            fromNormalHead: 4
            fromNotchHead: 180
        
        disableNotchApples: false
    
    disableEnderpearlsDamages: true
    
    disableLevelIIPotions: false

    disableFoodRegeneration: true
    
    # If true a compass will show the nearest player, and the craft will be different.
    # Else, the craft will be standard and the compass will show the spawn point of the team/player (not the world spawn point).
    compass: true

teams-options:
    canSeeFriendlyInvisibles: true
    allowFriendlyFire: true

slow-start:
    delayBetweenTP: 3  # in seconds

dynmap:
    showSpawnLocations: true
    showDeathLocations: true

# Use this to set the spawnpoints of the teams (or the players)
# You can also use the command /uh addspawn (see /uh for documentation) to add temporary spawn points.
# (The spawn points added through /uh addspawn are deleted when the server is stopped.)
#
# Format:
#     - x,z
#     - x,z
#     - etc.

spawnpoints:
    -

# Use this to pre-register the teams.
# Format:
#     - color
#  -- OR --
#     - color,name

teams:
    -
